#Project 1 
# Chenxi Huang, Jingjing Feng, Weichuan Wu
# Divorce 


```{r}
#packages to use
install.packages("data.table")
install.packages("dplyr")
install.packages("plyr")
install.packages("Matrix")
install.packages("highcharter")
library(data.table)
library(dplyr)
library(plyr)
library(Matrix)
library(highcharter)
setwd("C:/Users/celia/Documents/2015 ActSci Course/2016 Fall/STAT5243 Applied Data Science/Project 1")
```

```{r}
# clean the data
varToKeep<-c("PWGTP","ST","SCHL","AGEP","SEX","MSP","WAGP","CIT","COW","WKHP","RAC1P","JWMNP","MARHT","MARHYP","RETP","ANC","DIS","ESR","FOD1P","NATIVITY","OC","OCCP","PERNP","MAR","POVPIP","QTRBIR")
length(varToKeep)
data1<-fread('ss13pusa.csv',select = varToKeep)
data2<-fread('ss13pusb.csv',select = varToKeep)
dataAll<-rbind(data1,data2)
dim(dataAll)
```
```{r}
# change factors
dataAll$MAR <- factor(dataAll$MAR)
marryStatus <- c("Married","Widowed","Divorced","Separated","Never married or under 15 years old")
levels(dataAll$MAR) <- marryStatus

marriedData <- 
  dataAll%>%
  na.omit() %>%
  filter(MAR %in%c("Married","Widowed","Divorced","Separated"))
#marriedData is the total cleaned data we use
summary(marriedData$PERNP)
summary(marriedData)
class(marriedData)
dim(marriedData)

#divorce rate = people who have divorced/total marriagable people
Nation_DivRate=((sum(marriedData[marriedData$MAR != "Divorced" & marriedData$MARHT > 1,]$PWGTP))+sum(marriedData[marriedData$MAR=="Divorced",]$PWGTP))/(sum(marriedData$PWGTP))
Nation_DivRate
 
```
```{r}
# Education Level Vs Divorce
LessBachDegree=marriedData[marriedData$SCHL<21,]
BachDegree=marriedData[marriedData$SCHL==21,]
MasterDegree=marriedData[marriedData$SCHL==22,]
ProDegree=marriedData[marriedData$SCHL==23,]
DocDegree=marriedData[marriedData$SCHL==24,]
dim(LessBachDegree)
dim(BachDegree)
dim(MasterDegree)
dim(ProDegree)
dim(DocDegree)
# no one in the population has less than a bachelor's degree

# divorce rate in each group
LessBach_DivRate=((sum(LessBachDegree[LessBachDegree$MAR != "Divorced" & LessBachDegree$MARHT > 1,]$PWGTP))+sum(LessBachDegree[LessBachDegree$MAR=="Divorced",]$PWGTP))/(sum(LessBachDegree$PWGTP))
Bach_DivRate=((sum(BachDegree[BachDegree$MAR != "Divorced" & BachDegree$MARHT > 1,]$PWGTP))+sum(BachDegree[BachDegree$MAR=="Divorced",]$PWGTP))/(sum(BachDegree$PWGTP))
Master_DivRate=((sum(MasterDegree[MasterDegree$MAR != "Divorced" & MasterDegree$MARHT > 1,]$PWGTP))+sum(MasterDegree[MasterDegree$MAR=="Divorced",]$PWGTP))/(sum(MasterDegree$PWGTP))
Pro_DivRate=((sum(ProDegree[ProDegree$MAR != "Divorced" & ProDegree$MARHT > 1,]$PWGTP))+sum(ProDegree[ProDegree$MAR=="Divorced",]$PWGTP))/(sum(ProDegree$PWGTP))
Doc_DivRate=((sum(DocDegree[DocDegree$MAR != "Divorced" & DocDegree$MARHT > 1,]$PWGTP))+sum(DocDegree[DocDegree$MAR=="Divorced",]$PWGTP))/(sum(DocDegree$PWGTP))
LessBach_DivRate
Bach_DivRate
Master_DivRate
Pro_DivRate
Doc_DivRate

EduLevel = c("Less then Bachelor's Degree", "Bachelor's Degree","Master's Degree","Professional Degree","Doctorate Degree")
Edu_DivRate = cbind(0,Bach_DivRate,Master_DivRate,Pro_DivRate,Doc_DivRate)
# plot the graphs
highchart() %>% 
  hc_chart(type = "funnel") %>% 
  hc_add_series(
    name = "Education Level Vs Divorce Rate",
    data = list_parse(
      data.frame(
        name = EduLevel),
        y = Edu_DivRate
      )
    )
  )


```
```{r}

```

